import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "rest/microsoft/express-pnp",
    },
    {
      type: "category",
      label: "Sharepoint",
      items: [
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-webs-get-all-webs",
          label: "Sp.Sites.Webs.getAllWebs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-webs-create-one-web",
          label: "Sp.Sites.Webs.createOneWeb",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-webs-get-one-web",
          label: "Sp.Sites.Webs.getOneWeb",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-webs-update-one-web",
          label: "Sp.Sites.Webs.updateOneWeb",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-webs-delete-one-web",
          label: "Sp.Sites.Webs.deleteOneWeb",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-get-all-sites",
          label: "Sp.Sites.getAllSites",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-get-one-site-by-id",
          label: "Sp.Sites.getOneSiteById",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-update-one-site",
          label: "Sp.Sites.updateOneSite",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-delete-one-site",
          label: "Sp.Sites.deleteOneSite",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-create-one-site",
          label: "Sp.Sites.createOneSite",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-get-all-lists",
          label: "Sp.Sites.Lists.getAllLists",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-create-one-list",
          label: "Sp.Sites.Lists.createOneList",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-get-one-list-by-id",
          label: "Sp.Sites.Lists.getOneListById",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-update-one-list",
          label: "Sp.Sites.Lists.updateOneList",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-delete-one-list",
          label: "Sp.Sites.Lists.deleteOneList",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-get-all-items",
          label: "Sp.Sites.Lists.Items.getAllItems",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-create-one-item",
          label: "Sp.Sites.Lists.Items.createOneItem",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-get-one-item",
          label: "Sp.Sites.Lists.Items.getOneItem",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-update-one-item",
          label: "Sp.Sites.Lists.Items.updateOneItem",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-delete-one-item",
          label: "Sp.Sites.Lists.Items.deleteOneItem",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-get-all-fields",
          label: "Sp.Sites.Lists.Fields.getAllFields",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-create-one-field",
          label: "Sp.Sites.Lists.Fields.createOneField",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-get-one-field",
          label: "Sp.Sites.Lists.Fields.getOneField",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-update-one-field",
          label: "Sp.Sites.Lists.Fields.updateOneField",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-delete-one-field",
          label: "Sp.Sites.Lists.Fields.deleteOneField",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Web",
      items: [
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-webs-get-all-webs",
          label: "Sp.Sites.Webs.getAllWebs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-webs-create-one-web",
          label: "Sp.Sites.Webs.createOneWeb",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-webs-get-one-web",
          label: "Sp.Sites.Webs.getOneWeb",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-webs-update-one-web",
          label: "Sp.Sites.Webs.updateOneWeb",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-webs-delete-one-web",
          label: "Sp.Sites.Webs.deleteOneWeb",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Get",
      items: [
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-webs-get-all-webs",
          label: "Sp.Sites.Webs.getAllWebs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-webs-get-one-web",
          label: "Sp.Sites.Webs.getOneWeb",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-get-all-sites",
          label: "Sp.Sites.getAllSites",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-get-one-site-by-id",
          label: "Sp.Sites.getOneSiteById",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-get-all-lists",
          label: "Sp.Sites.Lists.getAllLists",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-get-one-list-by-id",
          label: "Sp.Sites.Lists.getOneListById",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-get-all-items",
          label: "Sp.Sites.Lists.Items.getAllItems",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-get-one-item",
          label: "Sp.Sites.Lists.Items.getOneItem",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-get-all-fields",
          label: "Sp.Sites.Lists.Fields.getAllFields",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-get-one-field",
          label: "Sp.Sites.Lists.Fields.getOneField",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Create",
      items: [
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-webs-create-one-web",
          label: "Sp.Sites.Webs.createOneWeb",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-create-one-site",
          label: "Sp.Sites.createOneSite",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-create-one-list",
          label: "Sp.Sites.Lists.createOneList",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-create-one-item",
          label: "Sp.Sites.Lists.Items.createOneItem",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-create-one-field",
          label: "Sp.Sites.Lists.Fields.createOneField",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Update",
      items: [
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-webs-update-one-web",
          label: "Sp.Sites.Webs.updateOneWeb",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-update-one-site",
          label: "Sp.Sites.updateOneSite",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-update-one-list",
          label: "Sp.Sites.Lists.updateOneList",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-update-one-item",
          label: "Sp.Sites.Lists.Items.updateOneItem",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-update-one-field",
          label: "Sp.Sites.Lists.Fields.updateOneField",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Delete",
      items: [
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-webs-delete-one-web",
          label: "Sp.Sites.Webs.deleteOneWeb",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-delete-one-site",
          label: "Sp.Sites.deleteOneSite",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-delete-one-list",
          label: "Sp.Sites.Lists.deleteOneList",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-delete-one-item",
          label: "Sp.Sites.Lists.Items.deleteOneItem",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-delete-one-field",
          label: "Sp.Sites.Lists.Fields.deleteOneField",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Site",
      items: [
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-get-all-sites",
          label: "Sp.Sites.getAllSites",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-get-one-site-by-id",
          label: "Sp.Sites.getOneSiteById",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-update-one-site",
          label: "Sp.Sites.updateOneSite",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-delete-one-site",
          label: "Sp.Sites.deleteOneSite",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-create-one-site",
          label: "Sp.Sites.createOneSite",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "List",
      items: [
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-get-all-lists",
          label: "Sp.Sites.Lists.getAllLists",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-create-one-list",
          label: "Sp.Sites.Lists.createOneList",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-get-one-list-by-id",
          label: "Sp.Sites.Lists.getOneListById",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-update-one-list",
          label: "Sp.Sites.Lists.updateOneList",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-delete-one-list",
          label: "Sp.Sites.Lists.deleteOneList",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-get-all-items",
          label: "Sp.Sites.Lists.Items.getAllItems",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-create-one-item",
          label: "Sp.Sites.Lists.Items.createOneItem",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-get-one-item",
          label: "Sp.Sites.Lists.Items.getOneItem",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-update-one-item",
          label: "Sp.Sites.Lists.Items.updateOneItem",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-delete-one-item",
          label: "Sp.Sites.Lists.Items.deleteOneItem",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-get-all-fields",
          label: "Sp.Sites.Lists.Fields.getAllFields",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-create-one-field",
          label: "Sp.Sites.Lists.Fields.createOneField",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-get-one-field",
          label: "Sp.Sites.Lists.Fields.getOneField",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-update-one-field",
          label: "Sp.Sites.Lists.Fields.updateOneField",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-delete-one-field",
          label: "Sp.Sites.Lists.Fields.deleteOneField",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Item",
      items: [
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-get-all-items",
          label: "Sp.Sites.Lists.Items.getAllItems",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-create-one-item",
          label: "Sp.Sites.Lists.Items.createOneItem",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-get-one-item",
          label: "Sp.Sites.Lists.Items.getOneItem",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-update-one-item",
          label: "Sp.Sites.Lists.Items.updateOneItem",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-items-delete-one-item",
          label: "Sp.Sites.Lists.Items.deleteOneItem",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Field",
      items: [
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-get-all-fields",
          label: "Sp.Sites.Lists.Fields.getAllFields",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-create-one-field",
          label: "Sp.Sites.Lists.Fields.createOneField",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-get-one-field",
          label: "Sp.Sites.Lists.Fields.getOneField",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-update-one-field",
          label: "Sp.Sites.Lists.Fields.updateOneField",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-fields-delete-one-field",
          label: "Sp.Sites.Lists.Fields.deleteOneField",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "UNTAGGED",
      items: [
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-folders-get-all-folders",
          label: "Sp.Sites.Lists.Folders.getAllFolders",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-folders-get-one-folder",
          label: "Sp.Sites.Lists.Folders.getOneFolder",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-folders-create-one-folder",
          label: "Sp.Sites.Lists.Folders.createOneFolder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-folders-delete-one-folder",
          label: "Sp.Sites.Lists.Folders.deleteOneFolder",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-folders-get-all-files-by-folder",
          label: "Sp.Sites.Lists.Folders.getAllFilesByFolder",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-folders-get-one-file-by-folder",
          label: "Sp.Sites.Lists.Folders.getOneFileByFolder",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-folders-create-one-file-by-folder",
          label: "Sp.Sites.Lists.Folders.createOneFileByFolder",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-folders-update-one-file-by-folder",
          label: "Sp.Sites.Lists.Folders.updateOneFileByFolder",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-folders-delete-one-file-by-folder",
          label: "Sp.Sites.Lists.Folders.deleteOneFileByFolder",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-files-get-all-files",
          label: "Sp.Sites.Lists.Files.getAllFiles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-files-create-one-file",
          label: "Sp.Sites.Lists.Files.createOneFile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-files-get-one-file",
          label: "Sp.Sites.Lists.Files.getOneFile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-files-update-one-file",
          label: "Sp.Sites.Lists.Files.updateOneFile",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-lists-files-delete-one-file",
          label: "Sp.Sites.Lists.Files.deleteOneFile",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-get-all-files",
          label: "Sp.Sites.getAllFiles",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-get-one-file",
          label: "Sp.Sites.getOneFile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-create-one-file",
          label: "Sp.Sites.createOneFile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-update-one-file",
          label: "Sp.Sites.updateOneFile",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "rest/microsoft/sp-sites-delete-one-file",
          label: "Sp.Sites.deleteOneFile",
          className: "api-method delete",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
